stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    - train_data.csv
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw 
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src/feature_engineering.py
    - data/interim
    outs:
    - data/processed

  model_building:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    - data/processed
    outs:
    - models/model.pkl

  models_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/model.pkl
    - data/processed
    metrics:
    - reports/metrics.json


